"""init tables

Revision ID: 2bb6312a5c9f
Revises: 
Create Date: 2026-06-09 10:35:20.189949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb6312a5c9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('is_moderator', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('toilets',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('yandex_place_id', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderator_reviews',
    sa.Column('toilet_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('score_cleanliness', sa.SmallInteger(), nullable=False),
    sa.Column('score_supplies', sa.SmallInteger(), nullable=False),
    sa.Column('score_smell', sa.SmallInteger(), nullable=False),
    sa.Column('score_equipment', sa.SmallInteger(), nullable=False),
    sa.Column('score_privacy', sa.SmallInteger(), nullable=False),
    sa.Column('score_vibe', sa.SmallInteger(), nullable=False),
    sa.Column('total_score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toilet_id', 'moderator_id', name='uq_mod_review_toilet_moderator')
    )
    op.create_table('reviews',
    sa.Column('toilet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score_cleanliness', sa.SmallInteger(), nullable=False),
    sa.Column('score_supplies', sa.SmallInteger(), nullable=False),
    sa.Column('score_smell', sa.SmallInteger(), nullable=False),
    sa.Column('score_equipment', sa.SmallInteger(), nullable=False),
    sa.Column('score_privacy', sa.SmallInteger(), nullable=False),
    sa.Column('score_vibe', sa.SmallInteger(), nullable=False),
    sa.Column('total_score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toilet_id', 'user_id', name='uq_review_toilet_user')
    )
    op.create_table('toilet_of_month',
    sa.Column('toilet_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_toilet_of_month_year_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toilet_of_month')
    op.drop_table('reviews')
    op.drop_table('moderator_reviews')
    op.drop_table('toilets')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
